GROQ_API_KEY="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"
OPENAI_API_KEY = "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"
LLAMA_CLOUD_API_KEY="llx-HgSAW8cqvMhmZWttDjdMbbuKiYKbojDkKCTgEDSwtRESQiYR"
SERPAPI_API_KEY="c8749605b3b5392608c0315f7cc1ded35106b8c3cc76085269d7e62d35eca224"